export const changePassword = '/user/password'
export const currentUserStatus = '/user/status'
export const userLogin = '/user/login'
export const userLogout = '/user/logout'
export const loginWithToken = '/user/token'
export const getCurrentIp = '/ip'
