export const currentUser = '/user/status'
export const myRecords = '/student/records'
export const changeEmail = '/student/email'
export const myTeacher = '/student/teacher'
export const lectures = '/student/lectures'
